docs:
- changed-files:
  - any-glob-to-any-file: '*.md'

api:
- changed-files:
  - any-glob-to-any-file: 'src/interface/rest/*'

src:
- changed-files:
  - any-glob-to-any-file: 'src/*'

script:
- changed-files:
  - any-glob-to-any-file: 'scripts/*'

asset:
- changed-files:
  - any-glob-to-any-file: 'assets/*'
