version: "3.6"
services:
  # CB-Spider
  cb-spider:
    image: cloudbaristaorg/cb-spider:0.9.0
    container_name: cb-spider
    platform: linux/amd64
    ports:
      - "1024:1024"
      - "2048:2048"
    volumes:
      # - ./conf/log_conf.yaml:/root/go/src/github.com/cloud-barista/cb-spider/conf/log_conf.yaml
      - ./conf/store_conf.yaml:/root/go/src/github.com/cloud-barista/cb-spider/conf/store_conf.yaml
      - ./container-volume/cb-spider-container/meta_db/:/root/go/src/github.com/cloud-barista/cb-spider/meta_db/
      - ./container-volume/cb-spider-container/log/:/root/go/src/github.com/cloud-barista/cb-spider/log/
    environment:
      - PLUGIN_SW=OFF
      # - SERVER_ADDRESS=localhost
      # if you leave these values empty, REST Auth will be disabled.
      - API_USERNAME=
      - API_PASSWORD=
      - SPIDER_LOG_LEVEL=error
      - SPIDER_HISCALL_LOG_LEVEL=error
      - ID_TRANSFORM_MODE=ON
    healthcheck: # for CB-Spider
      test: [ "CMD", "curl", "-f", "http://localhost:1323/tumblebug/readyz" ]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s

  # CB-Tumblebug
  cb-tumblebug:
    image: cloudbaristaorg/cb-tumblebug:0.9.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: cb-tumblebug
    platform: linux/amd64
    ports:
      - "1323:1323"
    depends_on: 
      - cb-spider
    volumes:
      - ./conf/:/app/conf/
      - ./container-volume/cb-tumblebug-container/meta_db/:/app/meta_db/
      - ./container-volume/cb-tumblebug-container/log/:/app/log/
    environment:
      - SPIDER_CALL_METHOD=REST
      - SPIDER_REST_URL=http://cb-spider:1024/spider
      # - DRAGONFLY_CALL_METHOD=REST
      # - DRAGONFLY_REST_URL=http://cb-dragonfly:9090/dragonfly
      - DB_URL=localhost:3306 
      - DB_DATABASE=cb_tumblebug 
      - DB_USER=cb_tumblebug 
      - DB_PASSWORD=cb_tumblebug 
      - ALLOW_ORIGINS=*
      - ENABLE_AUTH=true
      - API_USERNAME=default
      - API_PASSWORD=default
      - AUTOCONTROL_DURATION_MS=10000
      - SELF_ENDPOINT=localhost:1323
      - API_DOC_PATH=/app/src/api/rest/docs/swagger.json
      - DEFAULT_NAMESPACE=ns01
      - DEFAULT_CREDENTIALHOLDER=admin
      - LOGFILE_PATH=$CBTUMBLEBUG_ROOT/log/tumblebug.log
      - LOGFILE_MAXSIZE=10
      - LOGFILE_MAXBACKUPS=3
      - LOGFILE_MAXAGE=30
      - LOGFILE_COMPRESS=false
      - LOGLEVEL=debug
      - LOGWRITER=both
      - NODE_ENV=development
    healthcheck: # for CB-Tumblebug
      test: [ "CMD", "curl", "-f", "http://localhost:1323/tumblebug/readyz" ]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s

  # cb-mapui
  cb-mapui:
    image: cloudbaristaorg/cb-mapui:0.9.0
    container_name: cb-mapui
    ports:
      - "1324:1324"
    depends_on:
      - cb-tumblebug
    healthcheck: # for cb-mapui
      test: ["CMD", "nc", "-vz", "localhost", "1324"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s
