services:
  # etcd
  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.14
    container_name: etcd
    ports:
      - target: 2379       # Port assinged to etcd in the container
        published: 2379   # Port to be exposed to the host
        protocol: tcp     # Protocol of the port     
      - target: 2380      # Port assinged to etcd in the container
        published: 2380   # Port to be exposed to the host
        protocol: tcp     # Protocol of the port
    volumes: 
      - ./container-volume/etcd/data:/etcd-data
    entrypoint: /usr/local/bin/etcd
    command:
      - --name
      - s1
      - --data-dir
      - /etcd-data
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --initial-advertise-peer-urls
      - http://0.0.0.0:2380
      - --initial-cluster
      - s1=http://0.0.0.0:2380
      - --initial-cluster-token
      - tkn
      - --initial-cluster-state
      - new
      - --log-level
      - info
      - --logger
      - zap
      - --log-outputs
      - stderr
      - --auth-token
      - simple
    healthcheck: # for etcd
      test: [ "CMD", "/usr/local/bin/etcd", "--version"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  # etcd-conf
  etcd-conf:
    image: alpine:latest
    container_name: etcd-conf
    depends_on:
      - etcd
    volumes:
      - ./scripts/etcd/:/scripts/etcd/
    environment:
      - ETCD_VERSION_TAG=v3.5.14
      - ETCD_ENDPOINTS=http://etcd:2379
      - ETCD_PATH=/tmp/etcd-download-test
      - ETCD_AUTH_ENABLED=true
      - ETCD_ROOT_PASSWORD=default
      - ETCD_ADMIN_USERNAME=default
      - ETCD_ADMIN_PASSWORD=default
    command: sh -c "sh /scripts/etcd/etcd-conf.sh"
    healthcheck: # for etcd-conf
      test: ["CMD", "test", "-f", "/tmp/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # CB-Spider
  cb-spider:
    image: cloudbaristaorg/cb-spider:0.9.0
    container_name: cb-spider
    platform: linux/amd64
    ports:
      - target: 1024
        published: 1024
        protocol: tcp  
    volumes:
      # - ./conf/log_conf.yaml:/root/go/src/github.com/cloud-barista/cb-spider/conf/log_conf.yaml
      # - ./conf/store_conf.yaml:/root/go/src/github.com/cloud-barista/cb-spider/conf/store_conf.yaml
      - ./container-volume/cb-spider-container/meta_db/:/root/go/src/github.com/cloud-barista/cb-spider/meta_db/
      - ./container-volume/cb-spider-container/log/:/root/go/src/github.com/cloud-barista/cb-spider/log/
    environment:
      - PLUGIN_SW=OFF
      - SERVER_ADDRESS=localhost
      # if you leave these values empty, REST Auth will be disabled.
      # - API_USERNAME=
      # - API_PASSWORD=
      - SPIDER_LOG_LEVEL=error
      - SPIDER_HISCALL_LOG_LEVEL=error
      - ID_TRANSFORM_MODE=ON
    healthcheck: # for CB-Spider
      test: [ "CMD", "curl", "-f", "http://localhost:1024/spider/readyz" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  # CB-Tumblebug
  cb-tumblebug:
    image: cloudbaristaorg/cb-tumblebug:0.9.1
    pull_policy: missing
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cb-tumblebug
    platform: linux/amd64
    ports:
      - target: 1323
        published: 1323
        protocol: tcp
    depends_on: 
      - cb-spider
      - etcd-conf
    volumes:
      - ./conf/:/app/conf/
      - ./container-volume/cb-tumblebug-container/meta_db/:/app/meta_db/
      - ./container-volume/cb-tumblebug-container/log/:/app/log/
    environment:
      # - CBTUMBLEBUG_ROOT=/app
      # - SPIDER_CALL_METHOD=REST
      - SPIDER_REST_URL=http://cb-spider:1024/spider
      # - DRAGONFLY_CALL_METHOD=REST
      - DRAGONFLY_REST_URL=http://cb-dragonfly:9090/dragonfly
      # - DB_URL=localhost:3306 
      # - DB_DATABASE=cb_tumblebug 
      # - DB_USER=cb_tumblebug 
      # - DB_PASSWORD=cb_tumblebug 
      - TB_ETCD_ENDPOINTS=http://etcd:2379
      # - TB_ETCD_AUTH_ENABLED=true
      # - TB_ETCD_USERNAME=default
      # - TB_ETCD_PASSWORD=default
      # - ALLOW_ORIGINS=*
      # - AUTH_ENABLED=true
      # - API_USERNAME=default
      # - API_PASSWORD=default
      # - AUTOCONTROL_DURATION_MS=10000
      - SELF_ENDPOINT=localhost:1323
      # - API_DOC_PATH=/app/src/api/rest/docs/swagger.json
      # - DEFAULT_NAMESPACE=ns01
      # - DEFAULT_CREDENTIALHOLDER=admin
      # - LOGFILE_PATH=/app/log/tumblebug.log
      # - LOGFILE_MAXSIZE=10
      # - LOGFILE_MAXBACKUPS=3
      # - LOGFILE_MAXAGE=30
      # - LOGFILE_COMPRESS=false
      # - LOGLEVEL=debug
      # - LOGWRITER=both
      # - NODE_ENV=development
    healthcheck: # for CB-Tumblebug
      test: [ "CMD", "curl", "-f", "http://localhost:1323/tumblebug/readyz" ]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  # cb-mapui
  cb-mapui:
    image: cloudbaristaorg/cb-mapui:0.9.0
    container_name: cb-mapui
    ports:
      - target: 1324
        published: 1324
        protocol: tcp
    # depends_on:
    #   - cb-tumblebug
    healthcheck: # for cb-mapui
      test: ["CMD", "nc", "-vz", "localhost", "1324"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s
