tumblebug:
  endpoint: http://localhost:1323
  auth:
    info: auth.json
  demo:
    nsId: kdemo-ns01
    mciId: kdemo-mci01
  api:
    mciDynamic:
      reqBody: mciDynamic.json

terrarium:
  endpoint: http://localhost:8888
  auth:
    info: auth.json
  demo:
    terrariumId: kdemo-rg01
